openapi: 3.1.0
servers:
  - url: /api
info:
  version: 1.0.0
  title: Recipes
  description: An API to manage your favourite recipes
tags:
  - name: Recipes
    description: Everything about your recipes
  - name: User
    description: Everything related to the user
  - name: Meal Plan
    description: Define and fetch meal plans
  - name: Ingredients
    description: Everything about your ingredients
  - name: Units
    description: Everything about your units
  - name: Tags
    description: Everything about your tags
security:
  - cookieAuth: []
paths:
  /browse:
    get:
      tags:
        - Recipes
      summary: Browse public recipes
      operationId: browseRecipes
      responses:
        '200':
          description: Successful operation
          $ref: '#/components/responses/RecipeList'
        default:
          $ref: '#/components/responses/Error'
  /login:
    post:
      tags:
        - User
      security: []
      summary: Login a user
      operationId: login
      requestBody:
        description: Login a user with the provided credentials
        $ref: '#/components/requestBodies/Credentials'
      responses:
        '200':
          description: Successful operation
          $ref: '#/components/responses/AuthenticatedUser'
        default:
          $ref: '#/components/responses/Error'
  /logout:
    post:
      tags:
        - User
      summary: Logout a user
      operationId: logout
      responses:
        '200':
          description: Successful operation
          headers:
            'Set-Cookie':
              $ref: '#/components/headers/SessionCookie'
        default:
          $ref: '#/components/responses/Error'
  /register:
    post:
      tags:
        - User
      security: []
      summary: Register a new user
      operationId: register
      requestBody:
        description: The new user credentials
        $ref: '#/components/requestBodies/Credentials'
      responses:
        '204':
          description: Registration was successful
        default:
          $ref: '#/components/responses/Error'
  /user/confirm:
    post:
      tags:
        - User
      security: [ ]
      summary: Confirm a user account after successful registration
      operationId: confirmUser
      requestBody:
        $ref: '#/components/requestBodies/ConfirmUser'
      responses:
        '204':
          description: Successful operation
        default:
          $ref: '#/components/responses/Error'
  /user/password:
    post:
      tags:
        - User
      security: [ ]
      summary: Modify a user's password based on a reset token
      operationId: updatePassword
      requestBody:
        $ref: '#/components/requestBodies/PasswordReset'
      responses:
        '204':
          description: Successful operation
        default:
          $ref: '#/components/responses/Error'
  /user/password/reset:
    post:
      tags:
        - User
      security: []
      summary: Reset password for an existing user by email
      operationId: resetPassword
      requestBody:
        description: The user's email
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email
      responses:
        '204':
          description: Successful operation
        default:
          $ref: '#/components/responses/Error'
  /user/profile:
    get:
      tags:
        - User
      summary: Get the profile of the logged in user
      operationId: getUserProfile
      responses:
        '200':
          description: Successful operation
          $ref: '#/components/responses/User'
        default:
          $ref: '#/components/responses/Error'
  /mealplan:
    get:
      tags:
        - Meal Plan
      summary: Get your meal plan
      operationId: getMealPlan
      parameters:
        - name: from
          in: query
          description: From when to fetch the meal plan
          schema:
            type: string
            format: date
            example: '2023-01-01'
        - name: until
          in: query
          description: Until when to fetch the meal plan
          schema:
            type: string
            format: date
            example: '2023-01-01'
      responses:
        '200':
          description: Successful operation
          $ref: '#/components/responses/MealPlan'
        default:
          $ref: '#/components/responses/Error'
  /recipes:
    get:
      tags:
        - Recipes
      summary: Get all recipes
      operationId: getRecipes
      responses:
        '200':
          description: Successful operation
          $ref: '#/components/responses/RecipeList'
        default:
          $ref: '#/components/responses/Error'
    post:
      tags:
        - Recipes
      summary: Add a new recipe to the store
      operationId: addRecipe
      responses:
        '200':
          description: Successful operation
          $ref: '#/components/responses/Recipe'
        default:
          $ref: '#/components/responses/Error'
      requestBody:
        description: Create a new recipe in the store
        $ref: '#/components/requestBodies/Recipe'
  '/recipes/{recipeId}':
    get:
      tags:
        - Recipes
      summary: Find a recipe by ID
      description: Returns a single recipe
      operationId: getRecipeById
      parameters:
        - name: recipeId
          in: path
          description: ID of the recipe to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          $ref: '#/components/responses/Recipe'
        default:
          $ref: '#/components/responses/Error'
    post:
      tags:
        - Recipes
      summary: Updates a recipe in the store
      description: ''
      operationId: updateRecipe
      parameters:
        - name: recipeId
          in: path
          description: ID of the recipe to update
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        $ref: '#/components/requestBodies/Recipe'
      responses:
        '200':
          description: successful operation
          $ref: '#/components/responses/Recipe'
        default:
          $ref: '#/components/responses/Error'
    delete:
      tags:
        - Recipes
      summary: Deletes a recipe
      description: ''
      operationId: deleteRecipe
      parameters:
        - name: recipeId
          in: path
          description: Recipe ID to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        default:
          $ref: '#/components/responses/Error'
  '/recipes/{recipeId}/vote':
    post:
      tags:
        - Recipes
      summary: Vote on a recipe
      description: Cast an upvote (1) or downvote (-1) on a recipe
      operationId: addVote
      parameters:
        - name: recipeId
          in: path
          description: ID of the recipe to vote on
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        $ref: '#/components/requestBodies/Vote'
      responses:
        '200':
          description: successful operation
          $ref: '#/components/responses/RecipeVotes'
        default:
          $ref: '#/components/responses/Error'
    delete:
      tags:
        - Recipes
      summary: Remove vote from a recipe
      description: Remove your vote from a recipe
      operationId: removeVote
      parameters:
        - name: recipeId
          in: path
          description: ID of the recipe to remove vote from
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          $ref: '#/components/responses/RecipeVotes'
        default:
          $ref: '#/components/responses/Error'
  /ingredients:
    get:
      tags:
        - Ingredients
      summary: Get all ingredients
      operationId: getIngredients
      responses:
        '200':
          description: Successful operation
          $ref: '#/components/responses/IngredientList'
        default:
          $ref: '#/components/responses/Error'
  /units:
    get:
      tags:
        - Units
      summary: Get all units
      operationId: getUnits
      responses:
        '200':
          description: Successful operation
          $ref: '#/components/responses/UnitList'
        default:
          $ref: '#/components/responses/Error'
  /tags:
    get:
      tags:
        - Tags
      summary: Get all tags
      operationId: getTags
      responses:
        '200':
          description: Successful operation
          $ref: '#/components/responses/TagList'
        default:
          $ref: '#/components/responses/Error'
components:
  headers:
    SessionCookie:
      description: Sets the session for the logged in user
      schema:
        type: string
        examples:
          - SESSID=123; Path=/; HttpOnly
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: SESSID
  schemas:
    Credentials:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          examples:
            - test@example.com
        password:
          type: string
          examples:
            - Spaghetti Carbonara
    Error:
      type: object
      description: Represents an error
      properties:
        message:
          type: string
      required:
        - message
    Ingredient:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          examples:
            - 10
        name:
          type: string
          examples:
            - Flour
    PasswordReset:
      allOf:
        - $ref: '#/components/schemas/Token'
        - type: object
          required:
            - password
          properties:
            password:
              type: string
              examples:
                - my new password
    ReadMealPlan:
      type: object
      required:
        - date
      properties:
        date:
          type: string
          description: When are these recipes planned
          examples:
            - 2006-06-01
        recipes:
          type: array
          items:
            $ref: '#/components/schemas/ReadRecipe'
    ReadRecipe:
      allOf:
        - $ref: '#/components/schemas/BaseRecipe'
        - type: object
          required:
            - id
            - steps
            - votes
          properties:
            id:
              type: integer
              format: int64
              examples:
                - 10
            steps:
              type: array
              items:
                $ref: '#/components/schemas/ReadRecipeStep'
            tags:
              type: array
              items:
                $ref: '#/components/schemas/ReadTag'
            votes:
              $ref: '#/components/schemas/RecipeVotes'
    ReadUnit:
      type: object
      required:
        - id
        - name
        - code
      properties:
        id:
          type: integer
          format: int64
          examples:
            - 10
        name:
          type: string
          examples:
            - Kilogram
        code:
          type: string
          nullable: true
          examples:
            - kg
    ReadTag:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          examples:
            - 1
        name:
          type: string
          examples:
            - Vegetarian
    ReadUser:
      type: object
      required:
        - id
        - email
      properties:
        id:
          type: integer
          format: int64
          examples:
            - 10
        email:
          type: string
          examples:
            - user@example.com
    RecipeStatus:
      type: string
      description: Recipe status in the store
      enum:
        - available
        - pending
        - sold
    WriteRecipeStep:
      type: object
      required:
        - instructions
      properties:
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/WriteStepIngredient'
        instructions:
          type: string
          description: Textual instructions for this step
          examples:
            - "Put chicken into pan and cook on medium heat."
    ReadRecipeStep:
      type: object
      required:
        - id
        - instructions
      properties:
        id:
          type: integer
          format: int64
          examples:
            - 10
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/ReadStepIngredient'
        instructions:
          type: string
          description: Textual instructions for this step
          examples:
            - "Put chicken into pan and cook on medium heat."
    WriteStepIngredient:
      type: object
      required:
        - amount
        - ingredientId
        - unitId
      properties:
        ingredientId:
          type: integer
          format: int64
          examples:
            - 3
        unitId:
          type: integer
          format: int64
          examples:
            - 4
        amount:
          type: number
          format: float64
          examples:
            - 3.5
    ReadStepIngredient:
      type: object
      required:
        - amount
        - ingredient
        - unit
      properties:
        ingredient:
          $ref: '#/components/schemas/Ingredient'
        unit:
          $ref: '#/components/schemas/ReadUnit'
        amount:
          type: number
          format: float64
          examples:
            - 3.5
    Token:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          examples:
            - abd87ec862b6b8ecc2cf45c170d887d21e835a35f8537ea35ff1af102faa5920
    BaseRecipe:
      type: object
      required:
        - description
        - minutes
        - name
        - servings
      properties:
        name:
          type: string
          examples:
            - Spaghetti Carbonara
        description:
          type: string
          description: The HTML description of the recipe
          examples:
            - <p>My tasty spaghetti recipe</p>
        servings:
          type: integer
          format: int64
          description: How many servings you'll get with this recipe
          examples:
            - 4
        minutes:
          type: integer
          format: int64
          description: How long it takes to prepare this recipe (in minutes)
          examples:
            - 45
        images:
          type: array
          items:
            type: string
            format: uri
            examples:
              - https://example.com/spaghetti-carbonara.jpg
      encoding:
        images:
          contentType: image/jpeg, image/png
    WriteRecipe:
      allOf:
        - $ref: '#/components/schemas/BaseRecipe'
        - type: object
          required:
            - steps
          properties:
            steps:
              type: array
              items:
                $ref: '#/components/schemas/WriteRecipeStep'
            tags:
              type: array
              items:
                type: integer
                format: int64
                examples:
                  - 1
    Vote:
      type: object
      required:
        - vote
      properties:
        vote:
          type: integer
          format: int64
          description: Vote value (1 for upvote, -1 for downvote)
          enum: [1, -1]
          examples:
            - 1
    RecipeVotes:
      type: object
      required:
        - total
        - user
      properties:
        total:
          type: integer
          format: int64
          description: Total vote score (upvotes minus downvotes)
          examples:
            - 15
        user:
          type: integer
          format: int64
          description: Current user's vote on this recipe (1 for upvote, -1 for downvote, 0 if no vote)
          enum: [1, -1, 0]
          examples:
            - 1
  requestBodies:
    Credentials:
      description: User credentials
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Credentials'
    Recipe:
      description: Recipe object and related images
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/WriteRecipe'
    PasswordReset:
      description: The user's new password as well as the required reset token
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PasswordReset'
    ConfirmUser:
      description: The user's new password as well as the required reset token
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Token'
    Vote:
      description: Vote on a recipe
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Vote'
  responses:
    Error:
      description: Something went wrong
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    AuthenticatedUser:
      description: User object returned as result
      headers:
        'Set-Cookie':
          $ref: '#/components/headers/SessionCookie'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ReadUser'
    IngredientList:
      description: A list of ingredients
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Ingredient'
    UnitList:
      description: A list of units
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ReadUnit'
    TagList:
      description: A list of tags
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ReadTag'
    MealPlan:
      description: Meal plan for the user
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ReadMealPlan'
    RecipeList:
      description: Recipe object returned as result
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ReadRecipe'
    Recipe:
      description: Recipe object returned as result
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ReadRecipe'
    User:
      description: User object returned as result
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ReadUser'
    RecipeVotes:
      description: Recipe voting information
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RecipeVotes'